### ISSUE TITLE
How can I add the framework to a project manually?

### ISSUE THREAD

**Issue by AdamAliAU** [i-schuetz/PieCharts#13]
How can I add the framework to a project manually?

**Comment by i-schuetz** [comment]
The simplest way would be to just add the source code to your project. Download the project, copy and add the PieCharts folder into your project.

If you really want to add only the framework, build the framework target, go to the file (you can see it in xCode under "Products", right click and "Show in finder") and drag it to "Embedded binaries" in the general tab of your target (select "copy"). Note that the architecture you build for and where you use it has to be the same. Otherwise you need "fat" framework, like described [here](http://stackoverflow.com/questions/29634466/how-to-export-fat-cocoa-touch-framework-for-simulator-and-device). It's more convenient to use Carthage or CocoaPods in most cases.

**Comment by AdamAliAU** [comment]
for some reasons I had to add both the framework as well as the PieChart source code. All good now. thank you for your help.
